
const GEMINI_API_KEY = process.env.REACT_APP_GEMINI_API_KEY;

const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;

export const MANAGER_SYSTEM_CONTEXT = `
You are the Dentara Enterprise AI Assistant.

Your role is to help clinic managers analyze appointments, trends, performance, provider activity, and operational concerns.

Rules:
- Always complete your answer fully. Do not stop mid-sentence.
- Respond in plain text only.
- Do not use markdown, bullet points, or asterisks.
- Start with a direct answer, then give short supporting details.
- If counts or data exist, mention them clearly.
- If trend data is incomplete, explicitly say: "Trend data is limited or incomplete."
- Do not invent data.
- If data is missing, clearly say so.
- Keep answers concise and useful for a manager.

Tone:
- Professional and concise
- Manager-focused insights
`;

export const STAFF_SYSTEM_CONTEXT = `
You are the Dentara Staff AI Assistant.

Your role is to help clinic staff manage daily tasks, priorities, follow-ups, and pending work.

Rules:
- Always complete your answer fully. Do not stop mid-sentence.
- Respond in plain text only.
- Do not use markdown, bullet points, headings, or asterisks.
- Keep the response short and practical.
- Focus on the current staff member only.
- Focus on daily tasks, pending items, overdue work, priorities, and follow-ups.
- If there are no tasks due today, say that clearly first.
- Then also mention pending tasks, overdue tasks, and follow-up appointments if any exist.
- When asked about highest priority, choose the highest priority open task.
- Do not invent data.
- If data is missing, clearly say so.

Tone:
- Professional, clear, and actionable
- Staff-focused
`;

export const generateAIResponse = async (
  userPrompt,
  dataContext = "",
  systemContext = MANAGER_SYSTEM_CONTEXT
) => {
  if (!GEMINI_API_KEY) {
    console.error("Gemini API key is missing from .env file.");
    return "Error: AI configuration is missing. Please check the .env file.";
  }

  const engineeredPrompt = `
${systemContext}

CURRENT CLINIC DATA CONTEXT:
${dataContext}

USER QUESTION:
${userPrompt}
`;

  try {
    const response = await fetch(API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: engineeredPrompt }]
          }
        ],
        generationConfig: {
          maxOutputTokens: 500,
          temperature: 0.2
        }
      })
    });

    if (!response.ok) {
      throw new Error(`API Error: ${response.status}`);
    }

    const data = await response.json();

    if (
      data.candidates &&
      data.candidates.length > 0 &&
      data.candidates[0].content &&
      data.candidates[0].content.parts &&
      data.candidates[0].content.parts.length > 0
    ) {
      return data.candidates[0].content.parts[0].text;
    }

    return "No response generated by the AI.";
  } catch (error) {
    console.error("Error communicating with Gemini API:", error);
    return "Sorry, I am having trouble connecting to the Dentara AI service right now. Please try again later.";
  }
};